# Generated by Django 3.0.7 on 2020-07-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200728_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='last_company',
            field=models.CharField(default='Not Applicable', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_salary',
            field=models.CharField(default='Not Applicable', max_length=50),
        ),
    ]
