# Generated by Django 3.0.6 on 2020-07-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_job_candidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='candidate',
            new_name='candidates',
        ),
    ]
