# Generated by Django 3.0.6 on 2020-07-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200725_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='candidates',
        ),
    ]
