# Generated by Django 3.0.6 on 2020-07-25 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('main', '0005_remove_job_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='candidates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Candidate'),
        ),
    ]
