# Generated by Django 3.0.6 on 2020-07-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_job_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(max_length=50),
        ),
    ]
