# Generated by Django 3.0.7 on 2020-07-28 12:03

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200728_1254'),
        ('main', '0007_auto_20200727_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company_title', models.CharField(max_length=100)),
                ('job_loc', models.CharField(max_length=50)),
                ('job_sal', models.CharField(max_length=500)),
                ('job_exp', models.CharField(max_length=100)),
                ('job_des', models.TextField()),
                ('age', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=100)),
                ('pat_com', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=500)),
                ('g_period', models.CharField(max_length=500)),
                ('partners', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('current_City', models.CharField(max_length=200)),
                ('upload_Resume', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Commission')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Partner')),
            ],
        ),
    ]
