# Generated by Django 3.0.7 on 2020-07-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200731_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='current_City',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applyp',
            name='current_City',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='applyp',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
