# Generated by Django 3.0.6 on 2020-08-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200731_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='applyp',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='city',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='gender',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='timing',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commission',
            name='job_loc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_loc',
            field=models.CharField(max_length=500),
        ),
    ]
